// <auto-generated />
namespace ElanApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class House : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(House));
        
        string IMigrationMetadata.Id
        {
            get { return "201903251706026_House"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
